### ISSUE TITLE
Преобразовывать бинды в Source-стайл

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#10]
Нажал **End** -- записывается **kp_end**.
Нажал * -- записывается **kp_asterisk**.
И так далее для всех клавиш.

**Comment by moetelo** [comment]
@veselv2010 
как, есть идеи какие-нибудь?
их там не так много конечно в принципе. "буквенные" клавиши так и идут в бинд без изменения, а клавиши с кейпада и прочее говнище можно ручками в принципе понаходить.

**Comment by veselv2010** [comment]
@Shifu462 
Надо короче сделать, чтобы когда на окошко свободное кликаешь, пользователь нажимал клавишу на клавиатуре (как в любой игре), эта клавиша шла в словарь конвертирования сурс-биндов, и уже биндилась непосредственно в самой программе, ну, я так себе это представляю на данный момент.

**Comment by veselv2010** [comment]
![изображение](https://user-images.githubusercontent.com/32619716/81442979-3d15cd80-917d-11ea-9de3-c80f2033ccd5.png)

**Comment by veselv2010** [comment]
https://github.com/veselv2010/NowPlaying/blob/d6b0fd622f76b8e8c2b523fea4faff732e9e06eb/NowPlaying/WinAPIInputSender/KeySender.cs#L109 = https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netcore-3.1
