### ISSUE TITLE
jp => en 

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#12]
(kana => romaji)
Два решения:
1. Реализовать с помощью API какого-нибудь переводчика. С помощью него также можно конвертировать ru => en, что позволит обойти использование захардкоженого словаря, но необходимо наличие интернет-соединения.
2. Реализовать с помощью парсинга таблицы юникода. Этот метод я не выкупал, но видел, что так можно. Реализация более сложная, но возможно конвертирование в оффлайн режиме.

**Comment by moetelo** [comment]
а чё если въебашить либу ещё, чёто типа того:
https://github.com/Xifax/HiraKana/ 
?

**Comment by veselv2010** [comment]
это нам надо

**Comment by moetelo** [comment]
@veselv2010 
чего, покатит?
я бы ещё конечно погуглил, не стал рубить с плеча так сказать

**Comment by veselv2010** [comment]
@Shifu462 
С либой рациональнее всего получится

**Comment by moetelo** [comment]
@veselv2010 
Просто может другое что-то найти. Я всё мельком смотрел, не доходят руки погуглить основательно.
 
Что там с
> парсинга таблицы юникода

?
 
Можно линк или что, а то я не в теме. Как это вообще должно работать, что там парсить?
 
И в дотнете, кстати, точняк нет встроенных фич как раз под нашу issue?

**Comment by veselv2010** [comment]
@Shifu462 
https://www.codeproject.com/articles/87444/convert-japanese-string-to-romaji
Опять же, практически ничего еще не чекал по этому вопросу на данный момент, фича не первоочередная.
