### ISSUE TITLE
Замена токена по ходу работы (tokenSwapURL)

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#13]
https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/
Получение токена к API Spotify происходит лишь на моменте запуска программы. Необходимо обновлять его с периодичностью раз в час для корректной работы.

**Comment by moetelo** [comment]
Где-то была более исчерпывающая страница в их документации, не могу найти.

**Comment by moetelo** [comment]
https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow

**Comment by moetelo** [comment]
Половина работы захардкожена сквозь полусон в коммите https://github.com/veselv2010/NowPlaying/commit/a884eebad20b1d64ae93b8d0088398e7213b5feb. Нужно будет отрефакторить.
 
И допилить само обновление токена.

**Comment by moetelo** [comment]
Хотя у Рихтера можно найти похожий кусок кода:
![image](https://user-images.githubusercontent.com/17011936/50511975-c81e8800-0aa0-11e9-8bc1-65110bce3c53.png)
 
Если у него не зашквар, то почему бы и нет.

**Comment by moetelo** [comment]
Еб твою мать, не в ту issue написал коммент. Так ещё и закрыл.
