### ISSUE TITLE
design окна

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#14]
Сделать что-то из нынешнего нагромождения информации/кнопок => нормальный дизайн

- [x] Switch
- [x] Combobox
- [x] Checkbox
- [x] TextBox
- [x] (опционально) ProgressBar

**Comment by moetelo** [comment]
ну это надо у Илюхи например спросить, может чего подскажет или нарисует

**Comment by veselv2010** [comment]
https://www.figma.com/file/g1OgA6ec1RXhBPOGND4Yj7/jopa

**Comment by veselv2010** [comment]
d0121cdf88da7f1055025ef776a4eac1b88d033e
