### ISSUE TITLE
Уничтожить автомаппер

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#15]
Уничтожить автомаппер

**Comment by veselv2010** [comment]
@Shifu462 хуй знает, надо уничтожить его

**Comment by moetelo** [comment]
@veselv2010 
или может он идёт как зависимость от другой какой-то либы ?

**Comment by veselv2010** [comment]
@Shifu462 
Зависимость от какой-то неиспользуемой либы, уничтожаю.

**Comment by moetelo** [comment]
@veselv2010 
давай. а что за либа?

**Comment by moetelo** [comment]
Посмотри ещё внимательно, чтобы он ушёл из всех мест, в которых появился в коммите https://github.com/veselv2010/NowPlaying/commit/ac454a91840031286d759aad2f2353eb3fb96b2f.

**Comment by moetelo** [comment]
красиво @veselv2010

**Comment by veselv2010** [comment]
@Shifu462 
Был связан с какой-то стим-хуетой

**Comment by moetelo** [comment]
https://github.com/veselv2010/NowPlaying/commit/ad813a4c1e3d3889ed81376115afe3bfacaa48cf#diff-9ee82fc936286c627d7a2ce8f2a6b501R4
а это че за ебала?

**Comment by veselv2010** [comment]
@Shifu462 
Связано с окном IE (BrowserWindow.xaml.cs)
