### ISSUE TITLE
Вылет из-за отсутствия файла audio.cfg на другом аккаунте

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#17]
Вынес из #6.

**Comment by moetelo** [comment]
Как вариант, скопипиздить из https://stackoverflow.com/questions/10383053/create-file-if-file-does-not-exist и посмотреть, что получится. Всё же просто, вроде как.

**Comment by veselv2010** [comment]
Необходимо реализовать создание папок при их отсутствии
