### ISSUE TITLE
README.md в корне репозитория

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#18]
Написать краткую инструкцию по использованию программы => антизатуп

**Comment by veselv2010** [comment]
ef883594c894ae7e1768d9b5ddcace31027656b2

**Comment by moetelo** [comment]
а зачем на английском если у нас весь проект на русском

**Comment by moetelo** [comment]
или не весь

**Comment by seele402** [comment]
напишу вам redmi за сотку
