### ISSUE TITLE
Работа с одной кнопки

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#21]
На текущий момент программа работает следующим образом: необходимо нажать сначала бинд exec, затем бинд чата, так каждый раз. Необходимо реализовать "доправку" кнопки чата программой после нажатия кнопки exec, либо наоборот. Упоминается в #7

**Comment by moetelo** [comment]
Как надо:
1. Попросить пользователя забидить `exec audio` на какую-нибудь клавишу. Попросить его указать клавишу в нашей приложухе. (Назовём эту клавишу сейчас '{execKey}')
2. Записать бинд **bind {sayKey} say [Spotify] Now Playing: ...**. (Назовём эту клавишу `{sayKey}`).
3. `SendKey("{execKey}");` `SendKey("{sayKey}")`.
 
Примерно так?

**Comment by moetelo** [comment]
@veselv2010 
Я правильно понял, мы примерно так реализуем это всё?

**Comment by veselv2010** [comment]
@Shifu462 
да

**Comment by moetelo** [comment]
@veselv2010 
Затестишь пока, работает ли `SendKeys()` в кс вообще?

**Comment by veselv2010** [comment]
d7fe3abd159447b2fff235eda5ed44a3161ccb9d
