### ISSUE TITLE
F:\Steam\userdata\0\730\local\cfg\audio.cfg

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#26]
Что-то нажал, и директория сменилась на такую.
`\userdata\0\730\`
> userdata\0
 
Воспроизведу ошибку -- отредактирую описание.

**Comment by veselv2010** [comment]
@Shifu462  Появляется в том случае, если имя аккаунта есть в файле loginusers.vdf, а в папке userdata - нет. На практике такого возникать не должно, но желательно все же не показывать те аккаунты, папки в юзердате для которых не созданы.

**Comment by veselv2010** [comment]
Либо можно просто брать верный номер юзердаты при создании пути, это будет логичнее и проще.

**Comment by moetelo** [comment]
@veselv2010 
А в loginusers.vdf используется JSON?
Я просто думаю, что стоит не издеваться с Skip-Replace-Take и просто парсить как обычный JSON.

**Comment by veselv2010** [comment]
@Shifu462 
нет

**Comment by veselv2010** [comment]
решено в #30
