### ISSUE TITLE
Переделать многопоточность на ThreadPool

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#27]
![image](https://user-images.githubusercontent.com/17011936/50511611-5560dd00-0a9f-11e9-8cbc-49f6fd3d73da.png)

**Comment by moetelo** [comment]
А может быть это будет таска `Task`, которая определена где-то заранее, и она будет ожидать, если 
https://github.com/veselv2010/NowPlaying/blob/69ad074ec65865c586c3d1f233fa68582bb41079/NowPlaying/MainWindow.xaml.cs#L104
 
И просто продолжать выполнение, если свич снова включили.

**Comment by veselv2010** [comment]
#83
