### ISSUE TITLE
Извлечь метод из-под await Task.Factory.StartNew()

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#28]
https://github.com/veselv2010/NowPlaying/blob/8864a24e16dd64e99e02f06d558556b7b694e050/NowPlaying/MainWindow.xaml.cs#L85-L103

**Comment by moetelo** [comment]
Причины очевидны Никит или пояснить?

**Comment by moetelo** [comment]
@veselv2010 
Кратко:
1. **Рефакторинг**. Так красивее и понятнее.
2. **Оптимизация**. Не будет каждый раз создаваться анонимный метод. 
А он у нас сейчас создаётся вот так: 
`() => { ... }`

**Comment by veselv2010** [comment]
@Shifu462 
нам надо

**Comment by veselv2010** [comment]
неактуально
