### ISSUE TITLE
запретить изменять размеры окна

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#3]
нахуй

**Comment by veselv2010** [comment]
Как насчет скейлинга вместе с изменением размера окна

**Comment by moetelo** [comment]
@veselv2010 
как вариант. но зачем, интерфейс же не такой жирный. мало элементов!

**Comment by moetelo** [comment]
Починили в https://github.com/veselv2010/NowPlaying/commit/372cb47edf7630d93143ccc8144bc6c0158e2480
