### ISSUE TITLE
Алгоритм получения логинов пользователей

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#30]
После одного из обновлений в файл loginusers.vdf добавлена строка "WantsOfflineMode", причем она появляется в поле данного аккаунта только при смене статуса в самом стиме на этом аккаунте.
Необходимо найти более элегантный способ получения логинов пользователей.
![image](https://user-images.githubusercontent.com/32619716/55086268-23b8db80-50b9-11e9-801c-c6bc8b8c86fc.png)

**Comment by moetelo** [comment]
Соответственно, весь алг из https://github.com/veselv2010/NowPlaying/blob/cf33652130a7de9a6362116be3b1384ad2d5e2c1/NowPlaying/SteamidLooker.cs#L35 ломается, так как там берётся логин по номеру строки, грубо говоря. Так?

**Comment by moetelo** [comment]
У нас есть ручной способ добавления логина?
Или эта ищью ломает всю прогу?

**Comment by veselv2010** [comment]
Ломает ее практически полностью, за исключением первого аккаунта в списке.
![image](https://user-images.githubusercontent.com/32619716/55089254-2e29a400-50be-11e9-8884-4bbb54ac3222.png)
Ручного способа добавления логина у нас нет.

**Comment by veselv2010** [comment]
Один из вариантов: ввод логина самим пользователем, парсинг айди с файла loginusers.vdf лишь на введенный аккаунт.
