### ISSUE TITLE
Вылет при прослушивании с Local Files в спотифае

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#31]
https://github.com/veselv2010/NowPlaying/blob/f2d2e616606d28329b387d4eab55b72baa6bb3c1/NowPlaying/ApiResponses/CurrentTrackResponse.cs#L36
![image](https://user-images.githubusercontent.com/32619716/55288476-f32ab780-53c0-11e9-9010-98f9a2307f54.png)

**Comment by veselv2010** [comment]
При прослушивании с локал файлов стоит сделать чтение названия трека прямиком с названия окна спотифая, как это было в самом начале.

**Comment by moetelo** [comment]
1. ~~Что такое 'прослушивание с локал файлов'?~~
2. Остальные проперти кроме trackId не null?
Воспроизведи эту же ошибку, и когда вылетит эксепшн, почекай остальные переменные

**Comment by veselv2010** [comment]
Из всех проперти получает null только trackId, при удалении вывода эксепшена оно функционирует как положено.

**Comment by moetelo** [comment]
Лучше создай в `CurrentTrackResponse.cs`:

```cs
public bool IsLocalFile { get; }
```

В конструкторе:
```cs
this.IsLocalFile = this.Id == null;
```
