### ISSUE TITLE
Смена визибилити нагромождает код

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#33]
https://github.com/veselv2010/NowPlaying/blob/12b889761d18ae1ede5021270fef4942437dce72/NowPlaying/MainWindow.xaml.cs#L59-L65

https://github.com/veselv2010/NowPlaying/blob/12b889761d18ae1ede5021270fef4942437dce72/NowPlaying/MainWindow.xaml.cs#L87-L93

### ХУNНЯ

**Comment by moetelo** [comment]
https://refactoring.guru/ru/design-patterns/state
https://refactoring.guru/ru/design-patterns/state/csharp/example

**Comment by veselv2010** [comment]
запомни брат такую фразу все будет но не сразу
