### ISSUE TITLE
Не работает окно авторизации

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#37]
BrowserWindow.xaml.cs 42 line
![image](https://user-images.githubusercontent.com/32619716/55672197-e31f4600-58a0-11e9-990b-4bbf511e9b50.png)

**Comment by veselv2010** [comment]
Возможно проблема в самом IE11, в хроме страница с авторизацией отображается как положено
![image](https://user-images.githubusercontent.com/32619716/55674131-30a7ad00-58b9-11e9-8a40-934793da37de.png)

**Comment by moetelo** [comment]
Скорее всего проблема в arrow fuction в скрипте, на который ругается. (https://accounts.scdn.co/js/index.2a0d8f60176c3d43e699.js)
 
IE не поддерживает стрелочные функции.
![image](https://user-images.githubusercontent.com/17011936/55674603-65b6fe00-58bf-11e9-970c-54b52b4a2979.png)
 
Ругается на эту строку:
```js
const r=(e,t)=>new Promise(n=>{const r=()=>{t.test(document.readyState)&&(document.removeEventListener(e,r),n())};
```

Тут сразу три стрелочных функции.
 
Развёрнуто:
```js
const r = (e,t) => new Promise(n=>
{
    const r=()=>
    {
        t.test( document.readyState) && (document.removeEventListener(e,r),n() ) 
    };
```

**Comment by moetelo** [comment]
Пока разворачивал, заметил, что одной фигурной скобки не хватает.
![image](https://user-images.githubusercontent.com/17011936/55674657-1cb37980-58c0-11e9-847a-b707f2853c81.png)
![image](https://user-images.githubusercontent.com/17011936/55674661-22a95a80-58c0-11e9-9ef4-fa4ed1461e7e.png)

Может, новые браузеры переваривают и с ошибками, а ИЕ так не может? Может, в этом проблема?
 
Или я где-то что-то упустил, не докопировал строку.
