### ISSUE TITLE
Получение токена в хромиуме: уничтожить полную загрузку страницы ВК, так как мы токен получаем лишь из адресной строки

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#41]
https://github.com/veselv2010/NowPlaying/blob/158ae76df0486b689f71f3eec1c513f85514583b/NowPlaying/OAuth/BrowserWindow.xaml.cs#L36-L48

Этот ивентхэндлер вызывается после **полной** загрузки страницы, так как висит на ивенте `LoadingStateChanged`.
Нам это ни к чему: мы токен получаем из адресной строки, а сам контент страницы нам совсем не нужен.

Нужно подобрать другой ивент.
Кажется, это подойдёт:
http://cefsharp.github.io/api/57.0.0/html/E_CefSharp_OffScreen_ChromiumWebBrowser_AddressChanged.htm

**Comment by moetelo** [comment]
http://cefsharp.github.io/api/57.0.0/html/Events_T_CefSharp_OffScreen_ChromiumWebBrowser.htm

**Comment by moetelo** [comment]
да ваще прикольно было бы отловить `302 Redirect` и из его тела брать урл. если такое возможно ваще

**Comment by veselv2010** [comment]
loadingstatechanged так может
