### ISSUE TITLE
нечитабельный кусок кода с Aggregate

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#42]
https://github.com/veselv2010/NowPlaying/blob/598adef6e163c5205863b07abcea92bbf7ce1ff9/NowPlaying/TrackNameFormatter.cs#L10
=>
```csharp
return string.Join("", name.Select(ch => Ru2En[ch]))
```

Чем такой вариант не устроил @veselv2010?

**Comment by veselv2010** [comment]
не знаю я спиздил это со стаковерфлоу
