### ISSUE TITLE
Почистить KeySender

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#44]
В нем есть есть даже кнопки от геймпада, я думаю это можно удалить

**Comment by moetelo** [comment]
1. какие там элементы в енаме отвечают за геймпад?
2. откуда взят код с этим енамом?

**Comment by veselv2010** [comment]
1. XBUTTON1, 2
2. я спиздил это со стаковерфлоу

**Comment by moetelo** [comment]
@veselv2010 
в рамках этой задачи нужно вынести все классы и енамы в отдельные файлы

**Comment by moetelo** [comment]
желательно переименовать ещё структуры (если это возможно, если win32 не привязывается к неймингу) в нормальный ПаскальКейс
и проперти в них тоже по возможности переименовать

**Comment by veselv2010** [comment]
структуры не надо трогать
