### ISSUE TITLE
Браузер не выгружается из памяти после получения токена

### ISSUE THREAD

**Issue by veselv2010** [veselv2010/NowPlaying#45]
![изображение](https://user-images.githubusercontent.com/32619716/62836610-9d6af380-bc6d-11e9-9787-cbfffc2005ff.png)

**Comment by seele402** [comment]
лагает

**Comment by moetelo** [comment]
у меня есть подозрение что тут нужно обернуть вот это юзингом
https://github.com/veselv2010/NowPlaying/blob/345ae60400407c7185180a43da20d4703fd6b7a3/NowPlaying/UI/Windows/MainWindow.xaml.cs#L53-L54
```cs
using (var browserWindow = new BrowserWindow(_spotify))
{
...
}
```

**Comment by veselv2010** [comment]
#83
