### ISSUE TITLE
Закрывать программу, если !(IsCSGORunning() && IsSpotifyRunning())

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#6]
Если сейчас понажимать на кнопочки, то программа тупо вылетает с `NullReferenceException`.
 
Проверку, скорее всего, нужно добавить в **MainWindow.xaml.cs** в самое начало метода **Window_Loaded()**.
 
Также в **ProcessWorker.GetTrackFromSpotifyTitle()**:
```csharp
if (spotifyProcess == null)
    throw new ArgumentNullException("Spotify is not running.");
```
 
Также в любой метод, который использует эти процессы, добавить соответствующие проверки.
 
Или не закрывать, а предлагать включить CSGO/Spotify?
Тогда в те методы, которые как-то используют их, добавить появление какого-нибудь алёрта о том, что пользователь должен сперва включить эти штуки.

**Comment by moetelo** [comment]
Я бы остановился на последнем варианте. Хоть и первый проще.

**Comment by moetelo** [comment]
@veselv2010 что делаем?

**Comment by veselv2010** [comment]
@Shifu462  Могу только воспроизвести вылет со сменой аккаунта во время работы программы, можно пофиксить путем блокирования выбора аккаунта во время активного свитча.
Не вижу смысла в проверке "запущенности" CSGO/Spotify, предлагаю оставить это на потом.

**Comment by moetelo** [comment]
@veselv2010 
> вылет со сменой аккаунта во время работы программы

Какой эксепшн вылетает?

**Comment by veselv2010** [comment]
@Shifu462 
Вылет из-за отсутствия файла audio.cfg на другом аккаунте, повод сделать проверку перед записью

**Comment by moetelo** [comment]
@veselv2010 
Ну это не проблема, сделаем!
https://stackoverflow.com/questions/10383053/create-file-if-file-does-not-exist

**Comment by moetelo** [comment]
Мне кажется, стоит ещё вынести эту нехорошую часть пути `\730\local\cfg\audio.cfg` в `ConfigWriter` или ещё куда-нибудь.

**Comment by moetelo** [comment]
Или вообще из этого `SteamIdLooker.UserdataPath + $@"\{selectedaccountid.ToString()}\730\local\cfg\audio.cfg"` сделать темплейт пути и в него подставлять UserdataPath и selectedaccountid.

**Comment by veselv2010** [comment]
@Shifu462 
Cделать проверку стим процесса, как раз без него программа даже не запускается. Spotify может быть запущен на другом компьютере и проигрывать музыку, а программу можно запустить еще до запуска CSGO, ведь это удобнее, чем делать альтаб с самой игры. Короче, не думаю, что эти алерты будут нести какую-то пользу, а проверку стим процесса надо сделать обязательно.

**Comment by veselv2010** [comment]
На данный момент путь к стим-папке берется из реестра, без аккаунта в спотифае в главное окно не попасть, а путь к кфг с юзердаты даже создается при отсутствии конфигов с самой ксго. Закрываю за ненадобностью.
