### ISSUE TITLE
Автоматически отправлять название трека в чат при смене трека

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#7]
Бинды можно менять вечно. Нужно придумать, как всё-таки сделать так, чтобы оно автоматически работало. 
 
Но фичу с биндами оставить, разумеется. 
 
```csharp
if (trackResp.Id != LastTrackId)
  SendChatMessage() // грубо говоря
```

**Comment by moetelo** [comment]
@veselv2010 
Неясно даже то, куда копать.
Ты понимаешь, наверное, о чём я говорю: нужно сделать так, чтобы просто само отправлялось в чат, пока играешь.
Тупо отправлять нажатия клавиш не подходит (Y => *message* => Enter)

```csharp
SendKeys.Send("Y");
SendKeys.Send(message);
SendKeys.Send("{ENTER}"); // что-то такое
```

Так как игра будет приостанавливаться при открытии чата. Это помешает играть.
 
Нужно придумать что-то, что будет работать примерно так же, как какой-нибудь чит.
 
Может, можно найти где-то исходники чита, который спамит в чат? Подойдут исходники даже на C++. Разберёмся.
Или можно как-то самому узнать, что там происходит под капотом самой игры, когда сообщение отправляется?

**Comment by veselv2010** [comment]
Просто отправлять кнопку бинда, чат открывать не нужно

**Comment by moetelo** [comment]
@veselv2010 
Точняк! Звучит здраво.

**Comment by moetelo** [comment]
@veselv2010 
А что там нынче с той проблемой, что нужно постоянно в консоль писать `exec audio` (или что там)?

**Comment by veselv2010** [comment]
@Shifu462 
Перед каждым нажатием бинда на чат нужно прожимать кнопку с  биндом exec, иначе информация о треке не обновится (в самой игре). Можем сделать отправку клавиши exec после нажатия бинда чата, с задействием небольшой задержки прожатия чата, разумеется. Этот же принцип пойдет в автоматический спам (отправка двух кнопок).

**Comment by moetelo** [comment]
@veselv2010 
Понял.
> кнопку с биндом exec

Значит, пользователя нужно как-то уведомить о том, что он должен забиндить наш exec на какую-нибудь кнопку?

**Comment by veselv2010** [comment]
@Shifu462 
Да, надо бы написать readme, а то у тех, кто  первый раз использует это, происходит затуп.

**Comment by moetelo** [comment]
создай ищью, напишем потом кратко, чего и как

**Comment by moetelo** [comment]
@veselv2010 
Хорошо бы было вообще в самой приложе как-нибудь написать уведомление об этом!

**Comment by veselv2010** [comment]
@Shifu462
#19

**Comment by moetelo** [comment]
Зачем #21, если у нас есть эта?
Обе ищью об одном и том же, нет?

**Comment by veselv2010** [comment]
@Shifu462 
#7 - автоматическая отправка трека в чат по получении информации о его смене
#21 - нажатие одной кнопки вместо двух для отправки в чат
