### ISSUE TITLE
Создать .txt файл с темплейтом сообщения

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#8]
В котором будет лежать что-то вроде:
`[Spotify] Now Playing: {songname}`
 
А ConfigWriter будет оттуда брать этот темплейт в свою проперти 
```csharp
private string MessageTemplate { get; set; } = "bind \"{1}\" \"say [Spotify] Now Playing: {0}\"";
 
public void RefreshTemplateFromFile(string templateFilename = "messageTemplate.txt") 
{
    this.MessageTemplate = File.ReadAllText(templateFilename);
} // опять же от руки писал для того чтобы суть была понятна
```
 
А **RefreshTemplateFromFile()** вызываем в редких случаях (не в цикле `while (true)` 🅱️ ) чтобы не травмировать пеку постоянным доступом к файлу.

**Comment by veselv2010** [comment]
Имеется ввиду возможная кастомизация темплейта пользователем.

**Comment by moetelo** [comment]
👍
