### ISSUE TITLE
Выкинуть GlobalVariables.Ru2En в отдельный JSON файл.

### ISSUE THREAD

**Issue by moetelo** [veselv2010/NowPlaying#9]
Иначе это какое-то нагромождение кода.
 
Как вариант, можно сделать так:
Сам `Dictionary Ru2En` один раз сконвертировать в JSON через либу `Newtonsoft.Json`.
 
Вынести сам `Dictionary Ru2En` в **MessageFormatter**, и написать что-то вроде:
```csharp 
private static Dictionary<string, string> Ru2En { get; private set } = JsonConverter.Deserialize(File.ReadLines("Ru2En.json"))
// это псевдокод ебучий. писал от руки
```

**Comment by moetelo** [comment]
А может похуй.

**Comment by veselv2010** [comment]
согласен
